package org.sid.authenticationservice.payload;


import lombok.Data;

@Data
public class JwtRequest {
    private String username;
    private String password;

    // Constructor, Getters, and Setters are auto-generated by Lombok (@Data)
}
